### ISSUE TITLE
Scrolling cloud causes horizontal scroll

### ISSUE THREAD

**Issue by khwilson** [thepolicylab/initial-website#30]
![image](https://user-images.githubusercontent.com/1527442/80611765-0ca99300-8a09-11ea-8fa5-d5553920cd83.png)

![image](https://user-images.githubusercontent.com/1527442/80611939-4c707a80-8a09-11ea-88dd-e0294999484b.png)

When going to the home page and waiting a few seconds the scrolling cloud animation now causes the page to have a horizontal scroll available. See the above image. Firefox version above.

**Comment by jhogue** [comment]
The page has a div wrapper descendent of the body, class `.l-wrapper`, that has `overflow: hidden` on it. That used to be enough, but something changed. Will investigate.

**Comment by khwilson** [comment]
Works on my machine.
